spring:
  datasource:
    url:
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10Dialect
    open-in-view: false
#  rabbitmq:
#    host:
#    port:
#    username:
#    password:



#todo add test cases and readme file
# todo use gradle instead of maven